# SPDX-FileCopyrightText: © 2020 Phantom Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
#
# SPDX-License-Identifier: MIT

### At first perform source build ###
FROM phantomcash/phantom-wallet-builder-ubuntu-18-04:2.6 as build
MAINTAINER HLXEasy <hlxeasy@gmail.com>

# Build parameters
ARG BUILD_THREADS="6"

# Runtime parameters
ENV BUILD_THREADS=$BUILD_THREADS

COPY . /phantom-wallet

RUN cd /phantom-wallet \
 && ./scripts/cmake-build.sh -g -o -s -c ${BUILD_THREADS} \
 && strip /phantom-wallet/cmake-build-cmdline/phantomwallet/src/phantomwalletd \
 && strip /phantom-wallet/cmake-build-cmdline/phantomwallet/src/phantomwallet

### Now upload binaries to GitHub ###
FROM phantomcash/github-uploader:latest
MAINTAINER HLXEasy <hlxeasy@gmail.com>

ARG GITHUB_CI_TOKEN=1234567
ARG PHM_RELEASE=latest
ARG PHM_REPOSITORY=phantom-wallet
ARG GIT_COMMIT=unknown
ARG REPLACE_EXISTING_ARCHIVE=''
#ENV GITHUB_CI_TOKEN=${GITHUB_CI_TOKEN}
ENV ARCHIVE=Phantom-${PHM_RELEASE}-${GIT_COMMIT}-Ubuntu-18-04.tgz
ENV ARCHIVE_CHKSUM=Phantom-${PHM_RELEASE}-${GIT_COMMIT}-Ubuntu-18-04.sha256
ENV CHKSUM_FILE=Checksum-Phantom-Ubuntu-18-04.txt

RUN mkdir -p /filesToUpload/usr/local/bin

COPY --from=build /phantom-wallet/cmake-build-cmdline/phantomwallet/src/phantomwalletd /filesToUpload/usr/local/bin/phantomwalletd
COPY --from=build /phantom-wallet/cmake-build-cmdline/phantomwallet/src/phantomwallet /filesToUpload/usr/local/bin/phantomwallet
COPY --from=build /phantom-wallet/scripts/createChecksums.sh /tmp/

RUN cd /filesToUpload \
 && tar czf ${ARCHIVE} . \
 && github-release upload \
        --user phantomcash \
        --security-token "${GITHUB_CI_TOKEN}" \
        --repo "${PHM_REPOSITORY}" \
        --tag "${PHM_RELEASE}" \
        --name "${ARCHIVE}" \
        --file "/filesToUpload/${ARCHIVE}" \
        ${REPLACE_EXISTING_ARCHIVE} \
 && sha256sum /filesToUpload/${ARCHIVE} | awk '{ print $1 }' > /filesToUpload/${ARCHIVE_CHKSUM} \
 && cat /filesToUpload/${ARCHIVE_CHKSUM} \
 && github-release upload \
        --user phantomcash \
        --security-token "${GITHUB_CI_TOKEN}" \
        --repo "${PHM_REPOSITORY}" \
        --tag "${PHM_RELEASE}" \
        --name "${ARCHIVE_CHKSUM}" \
        --file "/filesToUpload/${ARCHIVE_CHKSUM}" \
        ${REPLACE_EXISTING_ARCHIVE} \
 && chmod +x /tmp/createChecksums.sh \
 && sh /tmp/createChecksums.sh /filesToUpload/${ARCHIVE} ${CHKSUM_FILE} \
 && export GITHUB_CI_TOKEN=---
