# SPDX-FileCopyrightText: © 2020 Phantom Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
#
# SPDX-License-Identifier: MIT

### At first perform source build ###
FROM phantomcash/phantom-wallet-builder-debian-stretch:2.6
MAINTAINER HLXEasy <hlxeasy@gmail.com>

# Build parameters
ARG BUILD_THREADS="6"

# Runtime parameters
ENV BUILD_THREADS=$BUILD_THREADS

COPY . /phantom-wallet

RUN cd /phantom-wallet \
 && ./scripts/cmake-build.sh -g -o -s -c ${BUILD_THREADS} \
 && strip /phantom-wallet/cmake-build-cmdline/phantomwallet/src/phantomwalletd \
 && strip /phantom-wallet/cmake-build-cmdline/phantomwallet/src/phantomwallet
