// SPDX-FileCopyrightText: © 2020 Phantom Developers
// SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
// SPDX-FileCopyrightText: © 2009 Bitcoin Developers
//
// SPDX-License-Identifier: MIT

#ifndef BRIDGETRANSLATIONS_H
#define BRIDGETRANSLATIONS_H
#include <QObject>

// Get strings in debug console `dumpStrings()`
// TODO: Automate this process, move into include and generate include...
static const char *html_strings[] = {
    QT_TRANSLATE_NOOP("phantom-bridge", "Overview"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Send"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Receive"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Transactions"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Address Book"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Options"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Add Sub-Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Immature generated coins with Proof-of-Work"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Advanced"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Backup Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Encrypt Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Change Passphrase"),
    QT_TRANSLATE_NOOP("phantom-bridge", "(Un)lock Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Tools"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Chain Data"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Block Explorer"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Sign Message"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Verify Message"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Debug"),
    QT_TRANSLATE_NOOP("phantom-bridge", "About Phantom"),
    QT_TRANSLATE_NOOP("phantom-bridge", "About QT"),
    QT_TRANSLATE_NOOP("phantom-bridge", "QR code"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Address:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Label:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Amount:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Add new receive address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Add Address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Add a new contact"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Address Lookup"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Address Type"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Stealth"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Group"),
    QT_TRANSLATE_NOOP("phantom-bridge", "BIP32"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Label"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Public Key"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Transaction Hash"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Recent Transactions"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Blockchain Info"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Coin Control"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Make payment"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Balance transfer"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Select Inputs"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Automatically selected"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Quantity:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Fee:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "After Fee:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Bytes:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Priority:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "LowOutput:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Change:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Custom change address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "From account"),
    QT_TRANSLATE_NOOP("phantom-bridge", "PUBLIC"),
    QT_TRANSLATE_NOOP("phantom-bridge", "PRIVATE"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Balance:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Ring Size:"),
    QT_TRANSLATE_NOOP("phantom-bridge", "To account"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Pay to"),
    QT_TRANSLATE_NOOP("phantom-bridge", "(no label)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Master"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Wallet is encrypted and currently locked"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Not staking because wallet is locked"),
    QT_TRANSLATE_NOOP("phantom-bridge", "0 active connection(s) to Phantom network"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a label for this address to add it to your address book"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a address to add it to your address book"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Inputs"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Values"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Outputs"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a Phantom address to sign the message with (e.g. SaKYqfD8J3vw4RTnqtgk2K9B67CBaL3mhV)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter the message you want to sign"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Click sign message to generate signature"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Copy the signed message signature"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a Phantom address to verify the message with (e.g. SaKYqfD8J3vw4RTnqtgk2K9B67CBaL3mhV)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter the message you want to verify"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a Phantom signature"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Paste signature from clipboard"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Your total balance"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Checking wallet state with network"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Recent in/out transactions or stakes"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Select inputs to spend"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Optional address to receive transaction change"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Choose from address book"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Paste address from clipboard"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Remove this recipient"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Send from public or private"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Current spendable send payment balance"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Send to public or private"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Current spendable balance to account"),
    QT_TRANSLATE_NOOP("phantom-bridge", "The label for this address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Amount to transfer"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Send to multiple recipients at once"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Date and time that the transaction was received."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Transaction status. Hover over this field to show number of confirmations."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Type of transaction."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Destination address of transaction."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Short payment note."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Amount removed from or added to balance."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Name for this Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a password"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Would you like to create a bip44 path?"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Your recovery phrase (Keep this safe!)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Recovery Phrase"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Wallet Name for recovered account"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter the password for the wallet you are trying to recover"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Is this a bip44 path?"),
    QT_TRANSLATE_NOOP("phantom-bridge", "ID"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Created"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Active Account"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Default"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Path"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Active"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Amount"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Note"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Public coins, visible on blockchain"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Private coins, untraceable and unlinkable on blockchain"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Available coins for spending"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Reserved coins are not used for staking"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Staked coins must mature before they can be accessed"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Public PHM requires 1 confirmation<br>Private PHM requires 10 confirmations"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Type"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Date"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Send Payment"),
    QT_TRANSLATE_NOOP("phantom-bridge", "The address to send the payment to"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a label for this address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Total Balance"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Balance"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Available"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Public"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Private"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Tor+OBFS4 connection online"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Wallet Encryption"),
    QT_TRANSLATE_NOOP("phantom-bridge", "A short reference for the recipient (max 24 characters)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "PHM Denomination Value"),
    QT_TRANSLATE_NOOP("phantom-bridge", "No. Owned (* = Immature)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "No. System Unspent (* = Immature)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "No. available Mixins (* = Immature)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "No. System (** = Compromised)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "The last block a coin of this denomination was created"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Owned (*)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Unspent (*)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Mixins (*)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "System (**)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Least Depth"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Value Out"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Value"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Addressbook"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Refresh"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Hash"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Height"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Timestamp"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a Phantom address (e.g. SXywGBZBowrppUwwNUo1GCRDTibzJi7g2M)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "An address label for the payment senders address book"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enter a short note to send with a payment (max 24 characters)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Filter by label or address..."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Note to send with payment (max 24 characters)"),
    QT_TRANSLATE_NOOP("phantom-bridge", "The private address to transfer the balance to"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Search by label or address"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Search"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Filter outputs"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Find Block by hash/height/transaction"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Family vacation funds"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Grouping will consolidate transactions of chosen"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Reset form"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Restore Sub-Wallet"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Stake"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Sub-Wallets"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Start Phantom on system login"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Detach databases at shutdown"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Pay transaction fee"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Transaction fee per kB. A higher fee makes sure your transactions are processed quickly in times of high transaction volume."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Most transactions are 1kB. The minimal fee is 0.0001"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enable Staking"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Enables or disables the staking process. If your wallet is encrypted, you will need to unlock it for staking."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Staking Donation"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Every sixth block on the blockchain is a development contribution block (DCB). Staking rewards of DCBs are contributed to the development fund no matter the donation percentage setting. Please feel free to additionally donate from your remaining stake rewards by defining a donation chance. Thank you."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Reserve"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Reserved amount does not participate in staking and is therefore spendable at any time."),
    QT_TRANSLATE_NOOP("phantom-bridge", "Minimum Stake Interval"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Main"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Window"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Display"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Minimize to the tray instead of the taskbar"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Minimize on close"),
    QT_TRANSLATE_NOOP("phantom-bridge", "User Interface language"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Unit to show amounts in"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Rows per page"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Display addresses in transaction list"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Notifications"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Visible Transaction Types"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Cancel"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Apply"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Ok"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Reserved"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Unconfirmed"),
    QT_TRANSLATE_NOOP("phantom-bridge", "Immature"),
//    QT_TRANSLATE_NOOP("phantom-bridge", ""),
//    QT_TRANSLATE_NOOP("phantom-bridge", ""),

    0 // Leave this here...
};
#endif // BRIDGETRANSLATIONS_H
