name: Featurebranch
on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - '*android*'

jobs:
  # ==========================================================================
  # Build MacOS version
  buildMacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.10'
          setup-python: 'false'
          modules: 'qtwebengine'

      - name: Install dependencies
        run: |
          brew install berkeley-db@4 boost leveldb openssl snappy

      - name: Cache build dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-build-dependencies-mac-v2
        with:
          path: |
            ${{ github.workspace }}/cmake-build-cmdline-mac/*
            !${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet
            ~/Archives/Tor/Tor.libraries.MacOS.zip
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Build MacOS binaries
        run: ./scripts/cmake-build-mac.sh -g
        env:
          MAC_QT_DIR: ${{ env.Qt5_DIR }}
