name: Featurebranch
on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - '*android*'

jobs:
  # ==========================================================================
  # Build Windows x64 version
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          setup-python: 'false'
          modules: 'qtwebengine'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.2
        with:
          vcpkgArguments: berkeleydb:x64-windows boost:x64-windows leveldb:x64-windows openssl:x64-windows
          vcpkgTriplet: x64-windows
          vcpkgDirectory: 'C:\vcpkg'
          vcpkgGitCommitId: aa028e94d733b03852ea441b2474468f43d94c5b

      - name: Build Windows binaries
        run: ./scripts/cmake-build-win.bat
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          QTDIR: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR: 'C:\Program Files\CMake\bin'
          VCPKGDIR: 'C:\vcpkg'
